Blue Sakura/Blue Sakura Website/Pages/FrontPage/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Blue_Sakura_Website.Pages.FrontPage
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Blue Sakura/Blue Sakura Website/Pages/FrontPage/IndividualPages.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Microsoft.AspNetCore.Http;
using Blue_Sakura_Logic.UserCollection;
using Blue_Sakura_Logic.EntertainmentCollection;
using Blue_Sakura_Logic.DAL;
using Blue_Sakura_Logic.PersonalEntertainmentCollection;

namespace Blue_Sakura_Website.Pages
{
    public class IndividualPagesModel : PageModel
    {
        [BindProperty]
        public User user { get; set; } = null;

        [BindProperty(SupportsGet = true)]
        public int EntertainmentID { get; set; }

        [BindProperty]
        public Entertainment Entertainment { get; set; } = null;

        public void OnGet()
        {
            if(EntertainmentID > 0)//add manga/anime check
            {
                Entertainment = EntertainmentDAL.GetEntertainment(EntertainmentID);
            }
            if (User.Identity.IsAuthenticated)
            {
                user = UserDAL.GetUser(Convert.ToInt32(Request.Cookies["UserID"]));
            }
        }

        public void OnGetAddPersonalEntertainment(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                user = UserDAL.GetUser(Convert.ToInt32(Request.Cookies["UserID"]));
                PersonalEntertainment personalEntertainment = new PersonalEntertainment(id);
                PersonalEntertainmentDAL.AddEntertainmentToPersonalEntertainment(user, personalEntertainment);
            }
            OnGet();
        }
    }
}

Blue Sakura/Blue Sakura Website/Pages/FrontPage/OverviewList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Microsoft.AspNetCore.Http;
using Blue_Sakura_Logic.UserCollection;
using Blue_Sakura_Logic.EntertainmentCollection;
using Blue_Sakura_Logic.DAL;
using Blue_Sakura_Logic.PersonalEntertainmentCollection;

namespace Blue_Sakura_Website.Pages
{
    public class OverviewListModel : PageModel
    {
        [BindProperty]
        public User user { get; set; } = null;

        [BindProperty]
        public List<Entertainment> Entertainments { get; set; } = new List<Entertainment>();

        public void OnGet()
        {
            Entertainments = EntertainmentDAL.GetAllEntertainment();

            if (User.Identity.IsAuthenticated)
            {
                user = UserDAL.GetUser(Convert.ToInt32(Request.Cookies["UserID"]));
            }
        }

        public void OnGetAddPersonalEntertainment(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                user = UserDAL.GetUser(Convert.ToInt32(Request.Cookies["UserID"]));
                PersonalEntertainment personalEntertainment = new PersonalEntertainment(id);
                PersonalEntertainmentDAL.AddEntertainmentToPersonalEntertainment(user, personalEntertainment);
            }
            OnGet();
        }
    }
}

Blue Sakura/Blue Sakura Website/Pages/FrontPage/SearchPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blue_Sakura_Logic.DAL;
using Blue_Sakura_Logic.UserCollection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Blue_Sakura_Website.Pages.FrontPage
{
    public class SearchPageModel : PageModel
    {
        [BindProperty]
        public List<User> Users { get; set; }

        public User user { get; set; } = null;

        [BindProperty(SupportsGet = true)]
        public string SearchInput { get; set; }

        public void OnGet()
        {
            if(SearchInput == null)
            {
                SearchInput = "";
            }
            Users = UserDAL.SearchUser(SearchInput);

            if(User.Identity.IsAuthenticated)
            {
                user = UserDAL.GetUser(Convert.ToInt32(Request.Cookies["UserID"]));
            }
        }
    }
}

Blue Sakura/Blue Sakura Website/Pages/FrontPage/ViewUserPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blue_Sakura_Logic.DAL;
using Blue_Sakura_Logic.PersonalEntertainmentCollection;
using Blue_Sakura_Logic.UserCollection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Blue_Sakura_Website.Pages.FrontPage
{
    public class ViewUserPageModel : PageModel
    {

        public User user { get; set; } = null;

        [BindProperty(SupportsGet = true)]
        public int UserID { get; set; }

        public List<PersonalEntertainment> personalEntertainments { get; set; } = new List<PersonalEntertainment>();

        public void OnGet()
        {
            user = UserDAL.GetUser(UserID);
            personalEntertainments = PersonalEntertainmentDAL.GetAllPersonalEntertainments(UserID);
        }
    }
}

Blue Sakura/Blue Sakura Website/Pages/FrontPage/ViewUserPersonalIndividualEntertainment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blue_Sakura_Logic.DAL;
using Blue_Sakura_Logic.EntertainmentCollection;
using Blue_Sakura_Logic.PersonalEntertainmentCollection;
using Blue_Sakura_Logic.UserCollection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Blue_Sakura_Website.Pages.FrontPage
{
    public class ViewUserPersonalIndividualEntertainmentModel : PageModel
    {
        public User user { get; set; }

        [BindProperty(SupportsGet = true)]
        public int EntertainmentID { get; set; }

        public Entertainment Entertainment { get; set; }

        public PersonalEntertainment PersonalEntertainment { get; set; }

        [BindProperty(SupportsGet = true)]
        public int UserID { get; set; }

        public void OnGet()
        {
            if (UserID > 0)
            {
                user = UserDAL.GetUser(UserID);
            }
            if (EntertainmentID > 0)
            {
                //get chosen personal entertainment
                PersonalEntertainment = PersonalEntertainmentDAL.GetPersonalEntertainment(UserID, EntertainmentID);
                Entertainment = EntertainmentDAL.GetEntertainment(PersonalEntertainment.EntertainmentID);
                Response.Cookies.Append("EntertainmentID", EntertainmentID.ToString());
            }
            else if (Request.Cookies["EntertainmentID"] != null)
            {
                EntertainmentID = Convert.ToInt32(Request.Cookies["EntertainmentID"]);
                PersonalEntertainment = PersonalEntertainmentDAL.GetPersonalEntertainment(user.Id, EntertainmentID);
                Entertainment = EntertainmentDAL.GetEntertainment(PersonalEntertainment.EntertainmentID);
            }
        }
    }
}

Blue Sakura/Blue Sakura Website/Pages/FrontPage/AccessDenied.cshtml
@page
@model Blue_Sakura_Website.Pages.FrontPage.AccessDeniedModel
@{
}

<h1 style="color:aliceblue;">Access Denied</h1>
<a asp-page="/index" style="text-decoration:none;color:aliceblue;">Back</a>

Blue Sakura/Blue Sakura Website/Pages/FrontPage/IndividualPages.cshtml
@page
@model Blue_Sakura_Website.Pages.IndividualPagesModel
@{
}

<a asp-page="/Index" class="back_button">Back</a>

<div class="individual_content_container">
    <div class="individual_content">

        <div class="individual_poster_container">
            <img src="~/img/@Model.Entertainment.Picture" class="individual_poster">
            <a asp-page-handler="AddPersonalEntertainment" asp-route-id="@Model.Entertainment.Id" asp-route-EntertainmentID="@Model.Entertainment.Id"><input type="button" id="add_button" value="+"></a>
        </div>

        <table class="individual_table">
            <tr>
                <td class="first_row">Title</td>
                <td class="second_row">@Model.Entertainment.Title</td>
            </tr>
            <tr>
                <td class="first_row">Alternate Title</td>
                <td class="second_row">@Model.Entertainment.AlternateTitle</td>
            </tr>
            <tr>
                <td class="first_row">Genre</td>
                <td class="second_row">@Model.Entertainment.Genre</td>
            </tr>
            <tr>
                <td class="first_row">Type</td>
                <td class="second_row">@Model.Entertainment.Type()</td>
            </tr>
            <tr>
                <td class="first_row">StartDate</td>
                <td class="second_row">@Model.Entertainment.GetStartDate</td>
            </tr>
            <tr>
                <td class="first_row">End Date</td>
                <td class="second_row">@Model.Entertainment.GetEndDate</td>
            </tr>
            <tr>
                <td class="first_row">Status</td>
                <td class="second_row">@Model.Entertainment.GetStatus()</td>
            </tr>
            <tr>
                <td class="first_row">Synopsis</td>
                <td class="second_row">@Model.Entertainment.Synopsis</td>
            </tr>
            @if (Model.Entertainment is Blue_Sakura_Logic.EntertainmentCollection.Anime)
            {
                <tr>
                    <td class="first_row">Studio</td>
                    <td class="second_row">@(((Blue_Sakura_Logic.EntertainmentCollection.Anime)Model.Entertainment).Studio)</td>
                </tr>
                <tr>
                    <td class="first_row">Episode</td>
                    <td class="second_row">@(((Blue_Sakura_Logic.EntertainmentCollection.Anime)Model.Entertainment).NrOfEpisode)</td>
                </tr>
                <tr>
                    <td class="first_row">Duration</td>
                    <td class="second_row">@(((Blue_Sakura_Logic.EntertainmentCollection.Anime)Model.Entertainment).GetDuration)</td>
                </tr>
                <tr>
                    <td class="first_row">Prequel</td>
                    @{
                        Blue_Sakura_Logic.EntertainmentCollection.Entertainment prequel = Blue_Sakura_Logic.DAL.EntertainmentDAL.GetAnime(((Blue_Sakura_Logic.EntertainmentCollection.Anime)Model.Entertainment).Prequel);
                        if (prequel == null)
                        {
                            <td class="second_row"></td>
                        }
                        else
                        {
                            <td class="second_row"><a class="anime_link" asp-page="/FrontPage/IndividualPages" asp-route-EntertainmentID="@prequel.Id">@prequel.Title</a></td>
                        }
                    }

                </tr>
                <tr>
                    <td class="first_row">Sequel</td>
                    @{
                        Blue_Sakura_Logic.EntertainmentCollection.Entertainment sequel = Blue_Sakura_Logic.DAL.EntertainmentDAL.GetAnime(((Blue_Sakura_Logic.EntertainmentCollection.Anime)Model.Entertainment).Sequel);
                        if (sequel == null)
                        {
                            <td class="second_row"></td>
                        }
                        else
                        {
                            <td class="second_row"><a class="anime_link" asp-page="/FrontPage/IndividualPages" asp-route-EntertainmentID="@sequel.Id">@sequel.Title</a></td>
                        }
                    }
                </tr>
            }
            else if (Model.Entertainment is Blue_Sakura_Logic.EntertainmentCollection.Manga)
            {
                <tr>
                    <td class="first_row">Author</td>
                    <td class="second_row">@(((Blue_Sakura_Logic.EntertainmentCollection.Manga)Model.Entertainment).Author)</td>
                </tr>
                <tr>
                    <td class="first_row">Volumes</td>
                    <td class="second_row">@(((Blue_Sakura_Logic.EntertainmentCollection.Manga)Model.Entertainment).Volumes)</td>
                </tr>
                <tr>
                    <td class="first_row">Chapters</td>
                    <td class="second_row">@(((Blue_Sakura_Logic.EntertainmentCollection.Manga)Model.Entertainment).Chapters)</td>
                </tr>
            }
        </table>

    </div>
</div>

Blue Sakura/Blue Sakura Website/Pages/FrontPage/OverviewList.cshtml
@page
@model Blue_Sakura_Website.Pages.OverviewListModel
@{
}

<div class="overview_container">

    <table class="overview_table">

        <tr class="overview_table_header">
            <th></th>
            <th>Title</th>
            <th>Genre</th>
            <th>Type</th>
        </tr>

        @foreach (Blue_Sakura_Logic.EntertainmentCollection.Entertainment e in Model.Entertainments)
        {
            <tr>
                <td><img src="~/img/@e.Picture" class="overview_poster"><a asp-page-handler="AddPersonalEntertainment" asp-route-id="@e.Id"></a></td>
                <td class="overview_table_title"><a asp-page="/FrontPage/IndividualPages" asp-route-EntertainmentID="@e.Id">@e.Title</a></td>
                <td>@e.GetMainGenre()</td>
                <td>@e.Type()</td>
            </tr>
        }

    </table>

</div>

Blue Sakura/Blue Sakura Website/Pages/FrontPage/SearchPage.cshtml
@page
@model Blue_Sakura_Website.Pages.FrontPage.SearchPageModel
@{
}

<div class="search_content">
    <form method="get">
        <input type="text" asp-for="SearchInput" />
        <a asp-page="/FrontPage/SearchPage" asp-route-SearchInput="@Model.SearchInput"><input type="submit" value="Search" /></a>
    </form>
</div>


<div class="overview_container">

    <table class="overview_table" style="font-size: 20px;">

        <tr class="overview_table_header">
            <th></th>
            <th style="font-size: 40px;">Username</th>
            <th style="font-size: 40px;">List</th>
        </tr>

        @foreach (Blue_Sakura_Logic.UserCollection.User u in Model.Users)
        {
            <tr>
                <td><img src="~/pfp/@u.Picture" class="overview_profile_picture"></td>
                <td class="overview_table_title"><a asp-page="/FrontPage/ViewUserPage" asp-route-UserID="@u.Id">@u.Username</a></td>
                <td><a asp-page="/FrontPage/ViewUserPage" asp-route-UserID="@u.Id" style="text-decoration: none; color: aliceblue;">View</a></td>
            </tr>
        }

    </table>

</div>

Blue Sakura/Blue Sakura Website/Pages/FrontPage/ViewUserPage.cshtml
@page
@model Blue_Sakura_Website.Pages.FrontPage.ViewUserPageModel
@{
}

<a asp-page="/FrontPage/SearchPage" class="back_button">Back</a>

<div class="title">
<h1>@Model.user.Username's List</h1>
</div>

<div class="overview_container">

    <table class="overview_table">

        <tr class="overview_table_header">
            <th></th>
            <th>Title</th>
            <th>Status</th>
            <th>Progress</th>
        </tr>

        @foreach (Blue_Sakura_Logic.PersonalEntertainmentCollection.PersonalEntertainment p in Model.personalEntertainments)
        {
            Blue_Sakura_Logic.EntertainmentCollection.Entertainment Entertainment = @Blue_Sakura_Logic.DAL.EntertainmentDAL.GetEntertainment(p.EntertainmentID);

            <tr>
                <td><img src="~/img/@Blue_Sakura_Logic.DAL.EntertainmentDAL.GetEntertainment(p.EntertainmentID).Picture" class="overview_poster"></td>
                <td class="overview_table_title"><a asp-page="/FrontPage/ViewUserPersonalIndividualEntertainment" asp-route-EntertainmentID="@p.EntertainmentID" asp-route-UserID="@Model.user.Id">@Entertainment.Title</a></td>
                <td>@p.Status</td>
                <td>
                    @p.Progress/
                    @if (Entertainment is Blue_Sakura_Logic.EntertainmentCollection.Anime)
                    {
                        @(((Blue_Sakura_Logic.EntertainmentCollection.Anime)Entertainment).NrOfEpisode)
                    }
                    else if (Entertainment is Blue_Sakura_Logic.EntertainmentCollection.Manga)
                    {
                        @(((Blue_Sakura_Logic.EntertainmentCollection.Manga)Entertainment).Chapters)
                    }
                </td>
            </tr>
        }

    </table>

</div>

Blue Sakura/Blue Sakura Website/Pages/FrontPage/ViewUserPersonalIndividualEntertainment.cshtml
@page
@model Blue_Sakura_Website.Pages.FrontPage.ViewUserPersonalIndividualEntertainmentModel
@{
}

<a asp-page="/FrontPage/ViewUserPage" asp-route-UserID="@Model.user.Id" class="back_button">Back</a>

<div class="individual_content_container">
    <div class="individual_content">

        <div class="individual_poster_container">
            <img src="~/img/@Model.Entertainment.Picture" class="individual_poster">
        </div>

        <table class="individual_table">
            <tr>
                <td class="first_row">Title</td>
                <td class="second_row"><a asp-page="/FrontPage/IndividualPages" asp-route-EntertainmentID="@Model.Entertainment.Id" style="text-decoration:none; color:aliceblue;">@Model.Entertainment.Title</a></td>
            </tr>
            <tr>
                <td class="first_row">Status</td>
                <td class="second_row">
                    @Model.PersonalEntertainment.Status
                </td>
            </tr>
            <tr>
                <td class="first_row">Progress</td>
                <td class="second_row">
                    @Model.PersonalEntertainment.Progress/
                    @if (Model.Entertainment is Blue_Sakura_Logic.EntertainmentCollection.Anime)
                    {
                        @(((Blue_Sakura_Logic.EntertainmentCollection.Anime)Model.Entertainment).NrOfEpisode)
                    }
                    else if (Model.Entertainment is Blue_Sakura_Logic.EntertainmentCollection.Manga)
                    {
                        @(((Blue_Sakura_Logic.EntertainmentCollection.Manga)Model.Entertainment).Chapters)
                    }
                </td>
            </tr>
        </table>

    </div>
</div>