Blue Sakura/Blue Sakura Website/Pages/PersonalPage/PersonalIndividualPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Blue_Sakura_Logic.UserCollection;
using Blue_Sakura_Logic.EntertainmentCollection;
using Blue_Sakura_Logic.DAL;
using Blue_Sakura_Logic.PersonalEntertainmentCollection;
using Blue_Sakura_Logic.EnumCollection;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Blue_Sakura_Website.Pages.PersonalPage
{
    public class PersonalIndividualPageModel : PageModel
    {
        public User user { get; set; }

        [BindProperty(SupportsGet = true)]
        public int EntertainmentID { get; set; }

        public Entertainment Entertainment { get; set; }
        
        public PersonalStatusType statusOption { get; set; }

        [BindProperty]
        public int SelectedStatus { get; set; }

        public List<SelectListItem> StatusList { get; set; }

        [BindProperty]
        public int Progress { get; set; }

        public PersonalEntertainment PersonalEntertainment { get; set; }

        public void OnGet()
        {
            if(User.Identity.IsAuthenticated)
            {
                user = UserDAL.GetUser(Convert.ToInt32(Request.Cookies["UserID"]));
            }
            if(EntertainmentID > 0)
            {
                //get chosen personal entertainment
                PersonalEntertainment = PersonalEntertainmentDAL.GetPersonalEntertainment(user.Id, EntertainmentID);
                Entertainment = EntertainmentDAL.GetEntertainment(PersonalEntertainment.EntertainmentID);
                Response.Cookies.Append("EntertainmentID", EntertainmentID.ToString());
                StatusList = StatusTypes(Entertainment);
                SelectedStatus = (int)PersonalEntertainment.Status;
            }
            else if(Request.Cookies["EntertainmentID"] != null)
            {
                EntertainmentID = Convert.ToInt32(Request.Cookies["EntertainmentID"]);
                PersonalEntertainment = PersonalEntertainmentDAL.GetPersonalEntertainment(user.Id, EntertainmentID);
                Entertainment = EntertainmentDAL.GetEntertainment(PersonalEntertainment.EntertainmentID);
                StatusList = StatusTypes(Entertainment);
            }
        }

        public IActionResult OnPost()
        {
            EntertainmentID = Convert.ToInt32(Request.Cookies["EntertainmentID"]);
            user = UserDAL.GetUser(Convert.ToInt32(Request.Cookies["UserID"]));
            PersonalEntertainment = PersonalEntertainmentDAL.GetPersonalEntertainment(user.Id, EntertainmentID);
            Entertainment = EntertainmentDAL.GetEntertainment(PersonalEntertainment.EntertainmentID);

            if (ModelState.IsValid)
            {
                PersonalEntertainment.Status = (PersonalStatusType)SelectedStatus;
                if (Entertainment is Blue_Sakura_Logic.EntertainmentCollection.Anime)
                {
                    if(Progress <= ((Blue_Sakura_Logic.EntertainmentCollection.Anime)Entertainment).NrOfEpisode)
                        PersonalEntertainment.Progress = Progress;
                    if (PersonalEntertainment.Status == PersonalStatusType.COMPLETED)
                        PersonalEntertainment.Progress = ((Blue_Sakura_Logic.EntertainmentCollection.Anime)Entertainment).NrOfEpisode;
                }
                
                else if(Entertainment is Blue_Sakura_Logic.EntertainmentCollection.Manga)
                {
                    if(Progress <= ((Blue_Sakura_Logic.EntertainmentCollection.Manga)Entertainment).Chapters)
                        PersonalEntertainment.Progress = Progress;
                    if (PersonalEntertainment.Status == PersonalStatusType.COMPLETED)
                        PersonalEntertainment.Progress = (int)((Blue_Sakura_Logic.EntertainmentCollection.Manga)Entertainment).Chapters;
                }

                PersonalEntertainmentDAL.UpdatePersonalEntertainment(user, PersonalEntertainment);
                return Redirect("/PersonalPage/PersonalListPage");
            }
            OnGet();
            return Page();
        }

        private static List<SelectListItem> StatusTypes(Entertainment entertainment)
        {
            List<SelectListItem> statuses = new List<SelectListItem>();
            if(entertainment is Blue_Sakura_Logic.EntertainmentCollection.Anime)
            {
                foreach(PersonalStatusType s in Enum.GetValues(typeof(PersonalStatusType)).Cast<PersonalStatusType>().ToList())
                {
                    if(s != PersonalStatusType.READING)
                    {
                        statuses.Add(new SelectListItem { Value = ((int)s).ToString(), Text = s.ToString()});
                    }
                }
            }
            else
            {
                foreach (PersonalStatusType s in Enum.GetValues(typeof(PersonalStatusType)).Cast<PersonalStatusType>().ToList())
                {
                    if (s != PersonalStatusType.WATCHING)
                    {
                        statuses.Add(new SelectListItem { Value = ((int)s).ToString(), Text = s.ToString() });
                    }
                }
            }
            return statuses;
        }
    }
}

Blue Sakura/Blue Sakura Website/Pages/PersonalPage/PersonalListPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Blue_Sakura_Logic.UserCollection;
using Blue_Sakura_Logic.EntertainmentCollection;
using Blue_Sakura_Logic.DAL;
using Blue_Sakura_Logic.PersonalEntertainmentCollection;
using Microsoft.AspNetCore.Http;

namespace Blue_Sakura_Website.Pages.PersonalPage
{
    public class PersonalListPageModel : PageModel
    {

        public User user { get; set; } = null;

        public List<PersonalEntertainment> personalEntertainments { get; set; } = new List<PersonalEntertainment>();

        public void OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                user = UserDAL.GetUser(Convert.ToInt32(Request.Cookies["UserID"]));
                personalEntertainments = PersonalEntertainmentDAL.GetAllPersonalEntertainments(user.Id);
            }
        }

        public void OnGetRemoveFromList(int entertainmentId)
        {
            //sql remove entertainment
            user = UserDAL.GetUser(Convert.ToInt32(Request.Cookies["UserID"]));
            PersonalEntertainmentDAL.RemovePersonalEntertainment(user, entertainmentId);
            OnGet();
        }
    }
}

Blue Sakura/Blue Sakura Website/Pages/PersonalPage/PersonalIndividualPage.cshtml
@page
@model Blue_Sakura_Website.Pages.PersonalPage.PersonalIndividualPageModel
@{
}

<a asp-page="/Index" class="back_button">Back</a>

<form method="post">
    <div class="individual_content_container">
        <div class="individual_content">

            <div class="individual_poster_container">
                <img src="~/img/@Model.Entertainment.Picture" class="individual_poster">
            </div>

            <table class="individual_table">
                <tr>
                    <td class="first_row">Title</td>
                    <td class="second_row"><a asp-page="/FrontPage/IndividualPages" asp-route-EntertainmentID="@Model.Entertainment.Id" style="text-decoration:none; color:aliceblue;">@Model.Entertainment.Title</a></td>
                </tr>
                <tr>
                    <td class="first_row">Status</td>
                    <td class="second_row">
                        <select asp-for="@Model.SelectedStatus" asp-items="Model.StatusList">
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="first_row">Progress</td>
                    <td class="second_row">
                        <input type="text" asp-for="Progress" value="@Model.PersonalEntertainment.Progress" />/
                        @if (Model.Entertainment is Blue_Sakura_Logic.EntertainmentCollection.Anime)
                        {
                            @(((Blue_Sakura_Logic.EntertainmentCollection.Anime)Model.Entertainment).NrOfEpisode)
                        }
                        else if (Model.Entertainment is Blue_Sakura_Logic.EntertainmentCollection.Manga)
                        {
                            @(((Blue_Sakura_Logic.EntertainmentCollection.Manga)Model.Entertainment).Chapters)
                        }
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td><a><input type="submit" value="save" style="padding:5px;border-radius:15px;background-color: aliceblue;"/></a></td>
                </tr>
            </table>

        </div>
    </div>
</form>

Blue Sakura/Blue Sakura Website/Pages/PersonalPage/PersonalListPage.cshtml
@page
@model Blue_Sakura_Website.Pages.PersonalPage.PersonalListPageModel
@{
}

<div class="overview_container">

    <table class="overview_table">

        <tr class="overview_table_header">
            <th></th>
            <th>Title</th>
            <th>Status</th>
            <th>Progress</th>
            <th></th>
        </tr>

        @foreach (Blue_Sakura_Logic.PersonalEntertainmentCollection.PersonalEntertainment p in Model.personalEntertainments)
        {
            Blue_Sakura_Logic.EntertainmentCollection.Entertainment Entertainment = @Blue_Sakura_Logic.DAL.EntertainmentDAL.GetEntertainment(p.EntertainmentID);

            <tr>
                <td><img src="~/img/@Blue_Sakura_Logic.DAL.EntertainmentDAL.GetEntertainment(p.EntertainmentID).Picture" class="overview_poster"></td>
                <td class="overview_table_title"><a asp-page="/PersonalPage/PersonalIndividualPage" asp-route-EntertainmentID="@p.EntertainmentID">@Entertainment.Title</a></td>
                <td>@p.Status</td>
                <td>
                    @p.Progress/
                    @if (Entertainment is Blue_Sakura_Logic.EntertainmentCollection.Anime)
                    {
                        @(((Blue_Sakura_Logic.EntertainmentCollection.Anime)Entertainment).NrOfEpisode)
                    }
                    else if (Entertainment is Blue_Sakura_Logic.EntertainmentCollection.Manga)
                    {
                        @(((Blue_Sakura_Logic.EntertainmentCollection.Manga)Entertainment).Chapters)
                    }
                </td>
                <td><a asp-page-handler="RemoveFromList" asp-route-entertainmentId="@p.EntertainmentID" style="text-decoration:none; color:aliceblue;">Remove</a></td>
            </tr>
        }

    </table>

</div>